#! /usr/bin/env python

import sys
import subprocess

args = sys.argv[1:]
for option_with_arg in ["-seat"]:
    if "-seat" in args:
        pos = args.index("-seat")
        args.pop(pos)
        args.pop(pos)

Xcommand = ["X.real"] +  args
print Xcommand
#subprocess.call(exec)
